### ISSUE TITLE
Using API to Create KB stripes out basic HTML supported tags

### ISSUE THREAD

**Issue by MaxAkbar** [Azure-Samples/cognitive-services-qnamaker-csharp#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Using the https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/quickstarts/create-new-kb-csharp sample create simple question and answer where there is a simple <p> tag t the answer. Then exeecute the code.

### Any log messages given by the failure
>The simple <p> tag is removed when viewing the KB in QnAMaker.ai.

### Expected/desired behavior
>The new imported KB should have the simple <p> tag.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>Windows 10

### Mention any other details that might be useful
If I use the CSV import the tag is preserved or if I manually update the answer. I need to use the API since there is a log of content and doing it manually is not an option. The CSV option seems only to allow one question\answer which is also not an option since my KB has multiple questions.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diberry** [comment]
I believe this issue is fixed, so closing. Please reopen if this issue continues.
