### ISSUE TITLE
Need to Add QnA Programmatically 

### ISSUE THREAD

**Issue by jaiswati** [Azure-Samples/cognitive-services-qnamaker-csharp#12]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Need to Add QnA Programmatically .. This returns UnAuthorized..
public  async Task<string> UpdateQueryQnABot(string newQuestion, string newAnswer)
        {
            string strResponse = "";
            // Create the QnAKnowledgeBase that contains the new entry
            QnAKnowledgeBase objQnAKnowledgeBase = new QnAKnowledgeBase();
            QnaPair objQnaPair = new QnaPair();

            objQnaPair.question = newQuestion;
            objQnaPair.answer = newAnswer;
           // if (paramMode == Mode.Add)
           // {
                Add objAdd = new Add();
                objAdd.qnaPairs = new List<QnaPair>();
                objAdd.urls = new List<string>();
                objAdd.qnaPairs.Add(objQnaPair);
                objQnAKnowledgeBase.add = objAdd;
           // }

            using (System.Net.Http.HttpClient client =
                new System.Net.Http.HttpClient())
            {
                string RequestURI = String.Format("{0}{1}{2}{3}? ",
                 @"https://westus.api.cognitive.microsoft.com/",
                  @"qnamaker/v4.0/",
                   @"knowledgebases/",
                   knowledgeBaseId);
                //https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/
                //string RequestURI = qnaServiceHostName + "/qnamaker/knowledgebases/" + knowledgeBaseId ;
                //string questionJSON = @"{'question': '" + question + "'}";

                using (HttpRequestMessage request =
                    new HttpRequestMessage(new HttpMethod("PATCH"), RequestURI))
                {
                    request.Content = new StringContent(
                        JsonConvert.SerializeObject(objQnAKnowledgeBase),
                        System.Text.Encoding.UTF8, "application/json");
                    request.Content.Headers.Add(
                        "Ocp-Apim-Subscription-Key", endpointKey);
                    HttpResponseMessage response = await client.SendAsync(request);
                    if (response.IsSuccessStatusCode)
                    {
                        strResponse = $"Operation successfully completed.";
                    }
                    else
                    {
                        string responseContent = 
                            await response.Content.ReadAsStringAsync();
                        strResponse = responseContent;
                    }

### Any log messages given by the failure
>

**Comment by diberry** [comment]
Please review new [quickstarts](https://github.com/Azure-Samples/cognitive-services-quickstart-code/tree/master/dotnet/QnAMaker).
