### ISSUE TITLE
Qna Maker api to fetch all the questions in qnaMaker

### ISSUE THREAD

**Issue by sathwikkrishna** [Azure-Samples/cognitive-services-qnamaker-csharp#21]
Hi, 
How do i get all the questions in the qnaMaker via an API.
There are about 1000 questions in my QnaMaker Knowledge i need to fetch all the questions via an api and store them in a SqlServer Db.

Thank you.

**Comment by diberry** [comment]
[Download kb](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.knowledge.qnamaker.iknowledgebase.downloadwithhttpmessagesasync?view=azure-dotnet)

**Comment by sathwikkrishna** [comment]
@diberry is there any api call and get the output of all questions.

**Comment by diberry** [comment]
@sathwikkrishna My understanding is that this is on the roadmap but not available now. #please-close
