### ISSUE TITLE
Replace QnA Maker Knowledgebase with Prompts 

### ISSUE THREAD

**Issue by MrLokeshV** [Azure-Samples/cognitive-services-qnamaker-csharp#22]
Hello Team,

I am trying to replace a knowledge base(multi turn enabled). But in API call i am getting the Error saying invalid prompts given.
It will be great help if you will provide the sample Json for Replace a qnA qith multiturn enabled

**Comment by diberry** [comment]
@MrLokeshV - Which API call did you use (SDK or REST, and which call inside of that) and what was returned?

**Comment by diberry** [comment]
Please review new [quickstarts](https://github.com/Azure-Samples/cognitive-services-quickstart-code/tree/master/dotnet/QnAMaker).
